apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: prod   
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: your-dockerhub/project-test-repo:1
        ports:
        - containerPort: 5000